/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author SMK TELKOM
 */
public class Kalkulator extends javax.swing.JFrame {

    String angka = "";
    double firstnum;
    double secondnum;
    double result;
    String operations; 
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBTN1 = new javax.swing.JButton();
        JBTN2 = new javax.swing.JButton();
        JBTN3 = new javax.swing.JButton();
        JBTN4 = new javax.swing.JButton();
        JBTN5 = new javax.swing.JButton();
        JBTN6 = new javax.swing.JButton();
        JBTN8 = new javax.swing.JButton();
        JBTN9 = new javax.swing.JButton();
        JBTN7 = new javax.swing.JButton();
        JBTN0 = new javax.swing.JButton();
        JBTNKALI = new javax.swing.JButton();
        JBTNMIN = new javax.swing.JButton();
        JBTNPLUS = new javax.swing.JButton();
        JBTNRESULT = new javax.swing.JButton();
        JTXTDISPLAY = new javax.swing.JTextField();
        JBTNBAGI = new javax.swing.JButton();
        JBTNCLEAR = new javax.swing.JButton();
        JBTNKOMA = new javax.swing.JButton();
        JBTNPERSEN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ini Kalkulator Lho");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Kalkulator ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 270, 50);

        JBTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN1.setText("1");
        JBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN1);
        JBTN1.setBounds(120, 90, 43, 30);

        JBTN2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN2.setText("2");
        JBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN2);
        JBTN2.setBounds(210, 90, 43, 30);

        JBTN3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN3.setText("3");
        JBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN3ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN3);
        JBTN3.setBounds(290, 90, 43, 30);

        JBTN4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN4.setText("4");
        JBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN4ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN4);
        JBTN4.setBounds(120, 130, 43, 31);

        JBTN5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN5.setText("5");
        JBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN5ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN5);
        JBTN5.setBounds(210, 130, 43, 31);

        JBTN6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN6.setText("6");
        JBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN6ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN6);
        JBTN6.setBounds(290, 130, 43, 31);

        JBTN8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN8.setText("8");
        JBTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN8ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN8);
        JBTN8.setBounds(210, 170, 43, 31);

        JBTN9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBTN9.setText("9");
        JBTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN9ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN9);
        JBTN9.setBounds(290, 170, 43, 30);

        JBTN7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN7.setText("7");
        JBTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN7ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN7);
        JBTN7.setBounds(120, 170, 43, 31);

        JBTN0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTN0.setText("0");
        JBTN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN0ActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN0);
        JBTN0.setBounds(240, 210, 43, 31);

        JBTNKALI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNKALI.setText("X");
        JBTNKALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNKALIActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNKALI);
        JBTNKALI.setBounds(240, 250, 45, 31);

        JBTNMIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNMIN.setText("-");
        JBTNMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNMINActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNMIN);
        JBTNMIN.setBounds(180, 250, 50, 31);

        JBTNPLUS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNPLUS.setText("+");
        JBTNPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNPLUSActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNPLUS);
        JBTNPLUS.setBounds(120, 250, 50, 30);

        JBTNRESULT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNRESULT.setText("=");
        JBTNRESULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNRESULTActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNRESULT);
        JBTNRESULT.setBounds(20, 310, 50, 30);

        JTXTDISPLAY.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTXTDISPLAY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(JTXTDISPLAY);
        JTXTDISPLAY.setBounds(90, 290, 250, 60);

        JBTNBAGI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBTNBAGI.setText("/");
        JBTNBAGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNBAGIActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNBAGI);
        JBTNBAGI.setBounds(290, 250, 40, 30);

        JBTNCLEAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNCLEAR.setText("Clear");
        JBTNCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNCLEARActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNCLEAR);
        JBTNCLEAR.setBounds(20, 250, 80, 31);

        JBTNKOMA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBTNKOMA.setText(".");
        JBTNKOMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNKOMAActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNKOMA);
        JBTNKOMA.setBounds(290, 210, 40, 31);

        JBTNPERSEN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBTNPERSEN.setText("%");
        JBTNPERSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNPERSENActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNPERSEN);
        JBTNPERSEN.setBounds(180, 210, 50, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("^2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 210, 50, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("MOD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 210, 80, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 350, 370);

        setSize(new java.awt.Dimension(395, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN1ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN1.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN1ActionPerformed

    private void JBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN3ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN3.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN3ActionPerformed

    private void JBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN2ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN2.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN2ActionPerformed

    private void JBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN4ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN4.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN4ActionPerformed

    private void JBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN5ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN5.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN5ActionPerformed

    private void JBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN6ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN6.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN6ActionPerformed

    private void JBTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN7ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN7.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN7ActionPerformed

    private void JBTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN8ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN8.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN8ActionPerformed

    private void JBTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN9ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN9.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN9ActionPerformed

    private void JBTN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN0ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTN0.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTN0ActionPerformed

    private void JBTNPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNPLUSActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        JTXTDISPLAY.setText("");
        operations = "+";
    }//GEN-LAST:event_JBTNPLUSActionPerformed

    private void JBTNMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNMINActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        JTXTDISPLAY.setText("");
        operations = "-";
    }//GEN-LAST:event_JBTNMINActionPerformed

    private void JBTNKALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNKALIActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        JTXTDISPLAY.setText("");
        operations = "*";
    }//GEN-LAST:event_JBTNKALIActionPerformed

    private void JBTNRESULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNRESULTActionPerformed
        // TODO add your handling code here:
       String answer;
       secondnum=Double.parseDouble(JTXTDISPLAY.getText());
       
       if (operations == "+"){
           result = firstnum+secondnum;
           answer = String.format("%.0f",result);
           JTXTDISPLAY.setText(answer);
       }
       else  if (operations == "-"){
           result = firstnum-secondnum;
           answer = String.format("%.0f",result);
           JTXTDISPLAY.setText(answer);
       }
       else  if (operations == "*"){
           result = firstnum*secondnum;
           answer = String.format("%.0f",result);
           JTXTDISPLAY.setText(answer);
       }
       else  if (operations == "/"){
           result = firstnum/secondnum;
           answer = String.format("%.0f",result);
           JTXTDISPLAY.setText(answer);
       }
       else if (operations == "%"){
           result = firstnum % secondnum;
           answer = String.format("%.0f",result);
           JTXTDISPLAY.setText(answer);
       }

    }//GEN-LAST:event_JBTNRESULTActionPerformed

    private void JBTNBAGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNBAGIActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        JTXTDISPLAY.setText("");
        operations = "/";
    }//GEN-LAST:event_JBTNBAGIActionPerformed

    private void JBTNCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNCLEARActionPerformed
        // TODO add your handling code here:
        JTXTDISPLAY.setText(null);
        firstnum=0;
        secondnum=0;
        result=0;
        
    }//GEN-LAST:event_JBTNCLEARActionPerformed

    private void JBTNKOMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNKOMAActionPerformed
        // TODO add your handling code here:
        String EnterNumber = JTXTDISPLAY.getText()+JBTNKOMA.getText();
        JTXTDISPLAY.setText(EnterNumber);
    }//GEN-LAST:event_JBTNKOMAActionPerformed

    private void JBTNPERSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNPERSENActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        angka = "";
        result = firstnum / 100;
            angka = Double.toString(result);
           JTXTDISPLAY.setText(angka);
    }//GEN-LAST:event_JBTNPERSENActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        angka = "";
        result = firstnum * firstnum;
            angka = Double.toString(result);
           JTXTDISPLAY.setText(angka);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(JTXTDISPLAY.getText());
        JTXTDISPLAY.setText("");
        operations = "%";
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN0;
    private javax.swing.JButton JBTN1;
    private javax.swing.JButton JBTN2;
    private javax.swing.JButton JBTN3;
    private javax.swing.JButton JBTN4;
    private javax.swing.JButton JBTN5;
    private javax.swing.JButton JBTN6;
    private javax.swing.JButton JBTN7;
    private javax.swing.JButton JBTN8;
    private javax.swing.JButton JBTN9;
    private javax.swing.JButton JBTNBAGI;
    private javax.swing.JButton JBTNCLEAR;
    private javax.swing.JButton JBTNKALI;
    private javax.swing.JButton JBTNKOMA;
    private javax.swing.JButton JBTNMIN;
    private javax.swing.JButton JBTNPERSEN;
    private javax.swing.JButton JBTNPLUS;
    private javax.swing.JButton JBTNRESULT;
    private javax.swing.JTextField JTXTDISPLAY;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
